In [30]:
import numpy as np

In [31]:
# Creaciion de una lista y creacion de un arreglo UNIDIMENCIONAL
lista1 = [1, 2, 3, 4, 5]
arreglo1 = np.array(lista1)
arreglo1

array([1, 2, 3, 4, 5])

In [32]:
type(arreglo1)

numpy.ndarray

In [33]:
# Creacion de un arreglo de una lista de listas y arreglos BIDIMENCIONALES
lista2 = [[1,2,3],
          [4,5,6],
          [7,8,9]]
arreglo2 = np.array(lista2)
arreglo2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
# las listas pueden tener diversos tipos de datos
lista = ['a', True, 1]
lista

['a', True, 1]

In [35]:
# Los arreglos solo pueden tener el type de dato
# usamos menos espacio en memoria
arreglo = np.array(lista)
arreglo         # Solo se almacenaron textos 
# notamos que le cambio el type a los datos solo dandoles comillas y los convirtio en STR 
# con la finalidad de usar menos memoria

array(['a', 'True', '1'], dtype='<U21')

In [ ]:
# creacion de arreglos con ceros    'utilizar doble parentesis'   'COMANDO .ZEROS'
arreglo3 = np.zeros((5,4))
arreglo3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
# Creacion de arreglos con numeros aleatorios uniformes entre 0 y 1     'COMANDO .RANDOM'
np.random.random((3,2))


array([[0.27546614, 0.30270018],
       [0.24976356, 0.52614296],
       [0.25541293, 0.53706607]])

In [38]:
# Creacion de arreglo en un rango       'COMANDO .ARANGE'
# NO se otorga el ultimo valor, en este caso es el numero 7
np.arange(-2,7)

array([-2, -1,  0,  1,  2,  3,  4,  5,  6])

In [39]:
np.arange(5)  # el ultimo valor nunca aparece, como es el caso con el 5 en este problema

array([0, 1, 2, 3, 4])

In [ ]:
arreglo1 = np.array([[1,2],
                    [5,7]])
arreglo2 = np.array([[8,9],
                     [5,7]])
arreglo2 = np.array([[1,2],
                     [5,7]])

In [51]:
# Arreglo bidimencional
arreglo_3D = np.array([arreglo1, arreglo2])
arreglo_3D

array([[[1, 2],
        [5, 7]],

       [[8, 9],
        [5, 7]]])

In [ ]:
arreglo3 = np.zeros((5,4))
arreglo3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# dimencion de este arreglo
arreglo3.shape

(5, 4)

In [54]:
# Conversion de un arreglo multi-dimencional a ini_dimencional
lista2 = [[1,2,3],
          [4,5,6],
          [7,8,9]]
arreglo2 = np.array(lista2)
arreglo2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
# Asi aplanamos los lementos
arreglo2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
# Cambio de dimencion de un arreglo
arreglo = np.array([[1,2],
                   [3,4],
                   [5,6]])
arreglo.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
# Ejemplo de ERROR al momneto de cambiar otra dimencion
arreglo.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [ ]:
# BIDIMENCIONAL cuando estamos hablando de solo 2 dimenciones
# TENSORES cuando estemos hablando de 3 o mas dimenciones

# Typos de datos en numpy

In [58]:
# EL atributo dtype   sirve para guardar el tipo de arreglo que vamos a guardar
np.array([1.25, 2.43, 200.88]).dtype

dtype('float64')

In [59]:
arreglo_int = np.array([[1,2,3], [4,5,6]])
arreglo_int.dtype

dtype('int64')

In [63]:
arreglo_string = np.array(['introduccion', 'a', 'la', 'programacion'])
arreglo_string.dtype

dtype('<U12')

In [65]:
# Uso de dtype como argumento
arreglo = np.array([1.25, 2.43, 200.88], dtype = np.float32) # mismo arreglo de arriba
arreglo.dtype
# con  esto havemos que utilizemos menos memoria con la idea de solo guardar una pequeña lista de numeros


dtype('float32')

In [66]:
 # cambio de typo de arreglo
arreglo_boleano = np.array([[True, False]], dtype = np.bool_)
arreglo_boleano.dtype

dtype('bool')

In [ ]:
# Comando de comvercion 'ASTYPE(NP.INT32)'
arreglo = arreglo_boleano.astype(np.int32)ç
arreglo

array([[1, 0]], dtype=int32)

In [ ]:
# Homologacion por typo de jerarquia de elementos 
# Aqui vemos que solo por tener un valor float, guarda los demas como float de 64bts
np.array([0, 50, 50.8]).dtype

dtype('float64')

In [71]:
np.array([False, 42])

array([ 0, 42])

# los valores de que menos ocupan son:   'DE MENOR A MAYOR'
# BOLEANOS
# ENTEROS
# FLOTANTES
# STRINGS