In [1]:
import numpy as np

In [2]:
# Indexacion de un solo elemento
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Extracciion de elementos en forma ascendente
x[2]

np.int64(2)

In [4]:
# Extraccion de elementos en forma decendente
x[-2]

np.int64(8)

In [5]:
x.shape = (2,5)   # Convercion de un arrego a bidimencional
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
x[1,3]      # Ectracion de elementos con indice 1 en renglon e indice 3 en columa  
# significa que el renglon 1 es la de abajo 
# y el 3 es la columna contando desde 0 al primer elemento hasta llegar al 3 que en eset caso es el numero 8

np.int64(8)

In [9]:
x[1][3] # Alternativa de extraccion del elemento con indice 1 en renglon e indice 3 en columa

np.int64(8)

In [10]:
x[1, -1]  # Extraccion de elementos con indice 1 en renglon y el primer elemento en forma decendente

np.int64(9)

In [11]:
x[0]   # Extraccion de renglon completo com indice 0 (al no especificar indice de columna).

array([0, 1, 2, 3, 4])

In [13]:
# cortes en arreglos
x = np.arange(10)
x[1:7:2]     # Formato: 'start:stop:step'
# EL ejemplo visual indica que el primer elemeto que le orotgamos es para dar el indice de  inicio
# el segundo elemento le indicamos donde nos vamos a detener 
# y el tercer elemento les estamos indicando el numero en el que iremos incrementando
# 0,1,2,3,4,5,6,7,8,9

array([1, 3, 5])

In [17]:
x[-2:10] # Corte del arreglo de adelnate hacia atras, considerando dos elementos
# Con el 10 de indicamos el numero donde queremos iniciar
# los dos puntos son cruciales ya que indica el seguimiento de elementos 
# en este caso el -2 es el numero de stop 
# indicando hasta donde queremos que llegue

array([8, 9])

In [20]:
x[-3:3:-1]  # Corte de arreglo de adelante hacia atras, iniciando 3 posiciones a partir del final
# Y retrocediendo de 1 en 1 
# Hasta llegar al 3 
# [1,2,3,4,5,6,7,8,9]

array([7, 6, 5, 4])

In [22]:
# Definicion de un nuevo arreglo
x = np.arange(10, 1, -1)   # Creacion de un arreglo en forma decendente - del 10 al 1 (sin escluirlo) 
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [23]:
# Extraccion de elementos especificos de un arreglo
x[np.array([3,3,1,8])] # Extraccion de elementos con indices 3, 3, 1, 8. 

array([7, 7, 9, 2])

In [24]:
x[np.array([3,3,-3,8])] # Extraccion de elementos con indices 3, 3, -3 (decendientes) y 8

array([7, 7, 4, 2])

In [26]:
# Extraccion basada en pares
y = np.arange(35).reshape(5,7)
y 

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [28]:
y[np.array([0,2,4]), np.array([[0,1,2]])] # Extraccion de 'cordenadas' (0,0), (2,1) y  (4,2)
# el primer array da las cordennadas de los renglones 
# el segundo array da las cordenadas de las columnas

array([[ 0, 15, 30]])

#### Union de arreglos

In [30]:
# Concatenacion de vectores
arr = np.concatenate(([1,2,3], [4,5,6]))
arr 

array([1, 2, 3, 4, 5, 6])

In [31]:
# Apliado vertical de vectores
np.stack(([1,2,3], [4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
# Concatenacion de matrices
mat_1 = np.array([[1,2,3], [4,5,6]])
mat_2 = np.array([[1,1,1], [2,2,2]])
np.concatenate((mat_1, mat_2), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [35]:
np.concatenate((mat_1, mat_2), axis=1)

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 2, 2, 2]])

In [36]:
np.concatenate((mat_1, mat_2), axis=None)

array([1, 2, 3, 4, 5, 6, 1, 1, 1, 2, 2, 2])

PRUEBA