In [2]:
import numpy as np
accidentes = np.array([[0,1,1],
                       [1,0,1],
                       [1,3,2],
                       [2,2,0]])

# EJERCICIOS
# Mediante el uso de un arreglo numpy determine:
# (a) numero total de accidentes durante los  4 años.
# (b) numero total de accidentes por area (columna).
# (c) el numero total de accidentes por año.
# (d) numero maximo y minimo de accidentes por area y año.
# (e) el numero promedio de accidentes por area y año

In [3]:
# Inciso (a)  # numero total de accidentes durante 4 años
# con el comando '.sum' nos da el total del valor de todas las columas
accidentes.sum()

np.int64(14)

In [4]:
# Inciso (b)    # numero total de accidentes por area (columna)
accid_areas = accidentes.sum(axis=0)
accid_areas

array([4, 6, 4])

In [5]:
# De esta forma tenemos los resultado mucho mas ordenada
print('los accidentes del area 1: ', accid_areas[0])
print('los accidentes del area 2: ', accid_areas[1])
print('los accidentes del area 3: ', accid_areas[2])

los accidentes del area 1:  4
los accidentes del area 2:  6
los accidentes del area 3:  4


In [6]:
# inciso (c)  # numero total de accidentes por año
accid_anios = accidentes.sum(axis=1)
accid_anios

array([2, 2, 6, 4])

In [7]:
# Conservacion de dimenciones para evitar confunciones
accid_anios = accidentes.sum(axis=1, keepdims=True)
accid_anios 

array([[2],
       [2],
       [6],
       [4]])

In [8]:
# De esta forma lo visualisamos de mejor manera.  # 
print('accidentes del año 1: ', accid_anios[0])
print('accidentes del año 2: ', accid_anios[1])
print('accidentes del año 3: ', accid_anios[2])
print('accidentes del año 4: ', accid_anios[3])

accidentes del año 1:  [2]
accidentes del año 2:  [2]
accidentes del año 3:  [6]
accidentes del año 4:  [4]


In [9]:
# Inciso (d)  # numero maximo y minimo de accidentes por area y año.
maximo = accidentes.max()
minimo = accidentes.min()
print(f'maximo de accidentes: {maximo}')
print(f'minimo de accidentes: {minimo}')

maximo de accidentes: 3
minimo de accidentes: 0


In [10]:
# Inciso (e)  # el numero promedio de accidentes por area y año
promedio = accidentes.mean()
print(f'promedio de accidentes: {promedio}')

promedio de accidentes: 1.1666666666666667


# Operaciones vectorizadas

### (a) un ciclo en python
### (b) una funcion vectorizada en Numpy

In [11]:
arreglo = np.array([[1,2,3],
                    [4,5,6]])
dimenciones = arreglo.shape
print(dimenciones[0])  # numero de renglones   '2'
print(dimenciones[1])   # numero de columnas      '3'
print(arreglo[0][0])    # primer elemento de todo el arreglo     '1'

2
3
1


In [12]:
# Inciso (a)    # un ciclo en python
import time
inicio = time.time()
arreglo_final = np.zeros((2,3))
for renglones in range(dimenciones[0]):
    for columnas in range(dimenciones[1]):
        arreglo_final[renglones][columnas] = arreglo[renglones][columnas] + 3
print(arreglo_final)

fin = time.time()
print('tiempo total de ejecucion (segs.'), fin - inicio

[[4. 5. 6.]
 [7. 8. 9.]]
tiempo total de ejecucion (segs.


(None, 0.0)

In [13]:
# Inciso (b)    # una funcion vectorizada en Numpy
import time
inicio = time.time()

arreglo_final = arreglo + 3
print(arreglo_final)

fin = time.time()
print('tiempo total de ejecucion (segs.'), fin - inicio

[[4 5 6]
 [7 8 9]]
tiempo total de ejecucion (segs.


(None, 0.0010857582092285156)

### Broadcasting

In [14]:
# Multiplicacion por un Escalar
arreglo_prod = arreglo * 3
arreglo_prod

array([[ 3,  6,  9],
       [12, 15, 18]])

In [15]:
# Adicion de Dos arreglos
arreglo1 = np.array([[1,2,3],
                     [4,5,6]])
arreglo2 = np.array([[7,8,9],
                     [10,11,12]])
arreglo3 = arreglo1 + arreglo2 
arreglo3

array([[ 8, 10, 12],
       [14, 16, 18]])

In [16]:
# Evaluacion de condiciones
arreglo1 = np.array([[1,2,3],
                     [4,5,6]])
arreglo1 > 2 

array([[False, False,  True],
       [ True,  True,  True]])

In [17]:
# Las funciones de python no estan vectorizadas de origen
# la funcion 'len' no esta factorizada de origen
# pero se puede factorizar
arreglo = np.array(['Numpy', 'Pandas', 'vetorizacion'])
len(arreglo) > 5

False

In [18]:
# Tranformacion para vectorizacion la funcion 'len'
len_vectorizada = np.vectorize(len)
len_vectorizada(arreglo) > 5

array([False,  True,  True])

In [19]:
# Broadcasting de renglones
arreglo = np.arange(10).reshape((2,5))
arreglo

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
# De esta froma le sumamos los valores al oprimer y segundo renglon 
# Broadcasting en suma de renglones
arreglo + np.array([0,1,2,3,4])

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [21]:
# Broadcasting de columnas
# 'NP.ARRAY(0,1)' Indica los valores que queremos que sean sumados
# 'RESHAPE(2,1)' indicamos primero el numero de renglones que queremos darle valores y el numero de columnas que usaremos en este caso es una. 
arreglo = np.arange(10).reshape((2,5))
arreglo + np.array([0,1]).reshape((2,1))

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [22]:
# Ejemplo de error
arreglo + np.array([0,1]) pass 

SyntaxError: invalid syntax (3247072668.py, line 2)

In [23]:
# Volteo a un arreglo
arreglo = np.array([[1.1,1.2,1.3],
                    [2.1,2.2,2.3],
                    [4.1,4.2,4.3]])
np.flip(arreglo)

array([[4.3, 4.2, 4.1],
       [2.3, 2.2, 2.1],
       [1.3, 1.2, 1.1]])

In [24]:
# Transposicion de un arreglo
arreglo = np.array([[1.1,1.2,1.3],
                    [2.1,2.2,2.3],
                    [4.1,4.2,4.3]])
np.transpose(arreglo)

array([[1.1, 2.1, 4.1],
       [1.2, 2.2, 4.2],
       [1.3, 2.3, 4.3]])

In [26]:
# Operacion #1
np.array([[1,2], [3,4]]) * np.array([[5],[10]])

array([[ 5, 10],
       [30, 40]])

In [29]:
# Operacion #2
np.array([[1,2], [3,4]]) - np.array([[5, 10]])

array([[-4, -8],
       [-2, -6]])